name: Deploy Laravel Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-deploy:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: laravel
          MYSQL_USER: user
          MYSQL_PASSWORD: secret
          MYSQL_ROOT_PASSWORD: secret
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, dom, filter, gd, iconv, json, mbstring, pdo
        
    - name: Copy .env
      run: cp .env.example .env
        
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      
    - name: Generate App Key
      run: |
        APP_KEY=$(php artisan key:generate --show)
        echo "APP_KEY=$APP_KEY" >> .env
        
    - name: Configure Environment
      run: |
        echo "DB_CONNECTION=mysql" >> .env
        echo "DB_HOST=127.0.0.1" >> .env
        echo "DB_PORT=3306" >> .env
        echo "DB_DATABASE=laravel" >> .env
        echo "DB_USERNAME=user" >> .env
        echo "DB_PASSWORD=secret" >> .env
        echo "APP_ENV=production" >> .env
        echo "APP_DEBUG=true" >> .env
        echo "APP_URL=https://diturie.github.io/ndc-lookup" >> .env
        
    - name: Directory Permissions
      run: |
        chmod -R 777 storage
        chmod -R 777 bootstrap/cache
        
    - name: Cache Configuration
      run: |
        php artisan config:cache
        php artisan route:cache
        php artisan view:cache
        
    - name: Run Database Migrations
      run: php artisan migrate --force --no-interaction

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install NPM dependencies
      run: |
        rm -rf node_modules
        rm -f package-lock.json
        npm cache clean --force
        npm install
      
    - name: Build assets
      run: |
        npm run build
        
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: public
        branch: gh-pages
        clean: true 