name: Deploy Laravel Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, dom, filter, gd, iconv, json, mbstring, pdo
        
    - name: Create Database Directory
      run: |
        mkdir -p database
        touch database/database.sqlite
        chmod -R 777 database
        
    - name: Setup Environment
      run: |
        cp .env.example .env
        echo "APP_KEY=base64:$(openssl rand -base64 32)" >> .env
        echo "DB_CONNECTION=sqlite" >> .env
        echo "DB_DATABASE=$GITHUB_WORKSPACE/database/database.sqlite" >> .env
        echo "APP_ENV=production" >> .env
        echo "APP_DEBUG=true" >> .env
        echo "APP_URL=https://diturie.github.io/ndc-lookup" >> .env
        cat .env
        
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      
    - name: Directory Permissions
      run: |
        chmod -R 777 storage
        chmod -R 777 bootstrap/cache
        chmod -R 777 database
        
    - name: Clear Configuration
      run: |
        php artisan config:clear
        php artisan cache:clear
        php artisan view:clear
        
    - name: Configure Application
      run: |
        echo "Current directory: $(pwd)"
        echo "Database exists: $(test -f database/database.sqlite && echo 'Yes' || echo 'No')"
        echo "Database permissions: $(ls -l database/database.sqlite)"
        php artisan migrate --force --no-interaction
        php artisan config:cache
        php artisan route:cache
        php artisan view:cache
        
    - name: Install NPM dependencies
      run: npm install --no-audit --no-fund --no-optional
      
    - name: Build assets
      run: |
        mkdir -p public/build
        npm run build
        
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: public
        branch: gh-pages
        clean: true 