name: Deploy Laravel Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, dom, filter, gd, iconv, json, mbstring, pdo
        
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      
    - name: Generate key
      run: |
        php artisan key:generate
        php artisan config:clear
        php artisan cache:clear
      
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
      
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
        chmod -R 777 database
      
    - name: Configure Application
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: /home/runner/work/ndc-lookup/ndc-lookup/database/database.sqlite
        APP_ENV: production
        APP_DEBUG: true
        APP_URL: https://diturie.github.io/ndc-lookup
      run: |
        php artisan migrate --force
        php artisan config:cache
        php artisan route:cache
        php artisan view:cache
        
    - name: Install NPM dependencies
      run: npm install --no-audit --no-fund --no-optional
      
    - name: Build assets
      run: |
        mkdir -p public/build
        npm run build
        
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: public
        branch: gh-pages
        clean: true 